spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
  security:
    user:
      password: 1

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace